version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    commit-message:
      prefix: ":arrow_up: chore:"
      include: scope
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: UTC
    commit-message:
      prefix: ":arrow_up: chore:"
      include: scope
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10